#!/bin/sh

# neovim for vim if available
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv xbps-install xbps-remove updatedb shutdown poweroff reboot ; do
	alias $command="doas $command"
done; unset command

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
}

# Some verbosity
alias \
        cp="cp -iv" \
        mv="mv -iv" \
        rm="rm -vI" \
        bc="bc -ql" \
        mkd="mkdir -pv" \
        yt="yt-dlp --embed-metadata -i" \
        ffmpeg="ffmpeg -hide_banner"

# Add some colors when you can
alias \
    	ls="ls -hN --color=auto --group-directories-first" \
        la="ls -A" \
        ll="ls -lhA" \
        grep="grep --color=auto" \
        ip="ip -color=auto" \
        diff="diff --color=auto"

# Some abbreviations
alias \
        ka="killall" \
        g="git" \
        sdn="shutdown -h now" \
        e="$EDITOR" \
        vi="$EDITOR" \
        i="xbps-install -S" \
        u="xbps-install -u xbps; xbps-install -Su" \
        r="xbps-remove" \
        q="xbps-query -Rs" \
        z="zathura" \
        nnn="nnn -Rr" \

# Some custom aliases
alias \
        dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME" \
        big="find / -type f -size +50M -exec du -h {} \; | sort -n"
