#!/bin/sh

alias e="${EDITOR:-vi}"
alias q="exit"

alias mkd="mkdir -pv"
alias cp="cp -iv"
alias ln="ln -iv"
alias mv="mv -iv"
alias rm="rm -Iv"
alias ls="ls -hF --color=auto --group-directories-first"
alias ll="ls -lA"
alias grep="grep --color=auto"
alias gr="grep --exclude-dir={.git,node_modules} -Hnr"

alias g="git"
alias gst="git status -sb"
alias gph="git push"
alias gpl="git pull"
alias gdf="git diff"

alias ip="ip -color=auto"
alias bc="bc -ql"
alias nnn="nnn -Rr"
alias diff="diff --color=auto"
alias info="info --vi-keys"
alias ccat="highlight -O ansi"
alias rsync="rsync -vrPlu"
alias ffmpeg="ffmpeg -hide_banner"
alias urls="grep -aohE '(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:;a-zA-Z0-9./+@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)'"
alias bm="buku --suggest"
alias drag="dragon-drop -x"

# pacman
alias pi="pacman -Sy"
alias pu="pacman -Syu"
alias pr="pacman -Rns"
alias pq="pacman -Ss"
alias pql="pacman -Qs"

# dotfiles management
alias config="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME"

# neovim for vim if available
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

sudocmd="$(command -v doas 2>/dev/null || command -v sudo 2>/dev/null)"
for cmd in mount umount sv xbps-install xbps-remove updatedb shutdown poweroff reboot zzz ZZZ vsv; do
	alias $cmd="$sudocmd $cmd"
done
unset sudocmd cmd
