#!/bin/sh

# neovim for vim if available
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# sudo not required for some system commands
sudocmd="sudo"
command -v doas >/dev/null 2>&1 && sudocmd="doas"
for cmd in su xbps-{install,remove} {,v}sv {,u}mount updatedb reboot poweroff shutdown; do
	alias $cmd="$sudocmd $cmd"
done
unset sudocmd cmd

# Some verbosity
alias \
        cp="cp -iv" \
        mv="mv -iv" \
        rm="rm -vI" \
        mkd="mkdir -pv" \
        yt="yt-dlp --embed-metadata -i" \
        ffmpeg="ffmpeg -hide_banner"

# Add some colors when you can
alias \
        ls="ls -hN --color=auto --group-directories-first" \
        grep="grep --color=auto" \
        ip="ip -color=auto" \
        diff="diff --color=auto"

# Some abbreviations
alias \
        ka="killall" \
        g="git" \
        sdn="shutdown -h now" \
        e="$EDITOR" \
        v="$EDITOR" \
        i="xbps-install -S" \
        u="i; xbps-install -u xbps; xbps-install -u" \
        r="xbps-remove -R" \
        q="xbps-query -Rs" \
        z="zathura" \
        nnn="nnn -Rr"

# Some custom aliases
alias \
        dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME" \
        big="find / -type f -size +50M -exec du -h {} \; | sort -n"
