#!/bin/sh

export BROWSER="brave"
export TERMINAL="st"
export EDITOR="nvim"
export VISUAL="nvim"

export PATH="$HOME/.local/bin:$HOME/script:$HOME/script/statusbar:$PATH"
export MANPAGER="nvim +Man!"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export NNN_FIFO="/tmp/nnn.fifo"
export NNN_PLUG="x:!chmod +x \$nnn*;y:-preview-tabbed"
export _JAVA_AWT_WM_NONREPARENTING=1


if [ -d "$HOME/.local/bin" ] ;
  then PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"
fi

if [ -d "/usr/local/go/bin" ] ;
  then PATH="$PATH:/usr/local/go/bin"
fi

if [ -d "/var/lib/flatpak/exports/bin/" ] ;
  then PATH="/var/lib/flatpak/exports/bin/:$PATH"
fi

if [ -d "$HOME/.cargo/bin" ] ;
  then PATH="$HOME/.cargo/bin:$PATH"
fi

[ -f $ZDOTDIR/.zshrc ] && . $ZDOTDIR/.zshrc
[[ ! $DISPLAY && $(tty) = "/dev/tty1" ]] && startx
