#!/bin/sh

xrdb "$XDG_CONFIG_HOME/x11/xresources" & xrdbpid=$!

xbacklight -set 20
xautolock -time 10 -locker slock &

# xwallpaper --zoom "$XDG_DATA_HOME/bg" >/dev/null 2>&1 &


[ -z "$SSH_AUTH_SOCK" ] && eval "$(ssh-agent -s)"
[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && eval "$(dbus-launch --exit-with-session --sh-syntax)"
dbus-update-activation-environment --all

for p in sxhkd pipewire dunst dwmblocks mpd "syncthing serve --no-browser"; do
	pidof -qsx "${p%% *}" || $p &
done >/dev/null 2>&1

wait $xrdbpid
xsetroot -solid "$(xrdb -get background)" &

exec dwm
